import { defineStore } from 'pinia'
import type { RecycleItemResponseDto, RestoredRecycleItemResponseDto } from '../../packages/api-client/src'
type Gateway = { list(): Promise<{ items: RecycleItemResponseDto[] }>; restore(id: string, version: number): Promise<RestoredRecycleItemResponseDto>; hardDelete(id: string, version: number, confirmed: boolean): Promise<{ deleted: boolean; id: string }> }
const errorFrom = (error: unknown) => ({ code: typeof (error as any)?.code === 'string' ? (error as any).code : 'RECYCLE_API_REQUEST_FAILED', message: error instanceof Error ? error.message : 'Recycle API request failed', status: typeof (error as any)?.status === 'number' ? (error as any).status : undefined, requestId: typeof (error as any)?.requestId === 'string' ? (error as any).requestId : undefined })
export const useRecycleStore = defineStore('recycle', { state: () => ({ items: [] as RecycleItemResponseDto[], loading: false, error: null as ReturnType<typeof errorFrom> | null, mutatingId: null as string | null }), actions: {
  async refresh(gateway: Pick<Gateway, 'list'>) { this.items = []; this.error = null; this.loading = true; try { this.items = (await gateway.list()).items } catch (error) { this.error = errorFrom(error) } finally { this.loading = false } },
  async restore(gateway: Pick<Gateway, 'restore'>, item: RecycleItemResponseDto) { this.error = null; this.mutatingId = item.id; try { await gateway.restore(item.id, item.version); this.items = this.items.filter((record) => record.id !== item.id); return true } catch (error) { this.error = errorFrom(error); return false } finally { this.mutatingId = null } },
  async hardDelete(gateway: Pick<Gateway, 'hardDelete'>, item: RecycleItemResponseDto, confirmed: boolean) { this.error = null; this.mutatingId = item.id; try { const result = await gateway.hardDelete(item.id, item.version, confirmed); if (result.deleted) this.items = this.items.filter((record) => record.id !== item.id); return result.deleted } catch (error) { this.error = errorFrom(error); return false } finally { this.mutatingId = null } },
} })
