<script setup lang="ts">
import type { AdminContentDetail } from "~/services/content/admin-content-detail";
import { useContentGateway } from "~/composables/useContentGateway";
import { useSessionStore } from "~/stores/session";

const props = defineProps<{ record?: AdminContentDetail }>();
const emit = defineEmits<{ saved: [id: string]; reload: [] }>();
const gateway = useContentGateway(); const session = useSessionStore();
const kind = ref(props.record?.kind ?? "article"); const centerId = ref(session.currentAccount?.adminCenterId ?? ""); const slug = ref(props.record?.id ?? ""); const title = ref(props.record?.title ?? ""); const summary = ref(props.record?.summary ?? ""); const body = ref(props.record?.blocks.filter((block) => block.type === "paragraph").map((block) => block.text).join("\n\n") ?? ""); const reason = ref(""); const error = ref(""); const notice = ref(""); const pending = ref(false); const reloadRequired = ref(false);
const isOwner = computed(() => session.adminLevel === "owner"); const canonicalBlocks = computed(() => [
  ...(body.value.trim() ? [{ type: "paragraph" as const, text: body.value.trim() }] : []),
  ...(props.record?.blocks.filter((block) => block.type === "image").map((block) => ({ type: "image" as const, attachmentId: block.attachmentId, alt: block.alt, ...(block.caption ? { caption: block.caption } : {}) })) ?? []),
]);
function fail(cause: unknown) { const api = cause as { status?: number; message?: string }; if (api.status === 409) { reloadRequired.value = true; error.value = "版本冲突：当前草稿已保留，请重新读取后再提交。"; } else error.value = api.message || "内容操作失败，请稍后重试。"; }
async function save() { if (!gateway || !title.value.trim() || !summary.value.trim()) { error.value = "请填写标题和摘要。"; return; } pending.value = true; error.value = ""; notice.value = ""; try { const result = props.record ? await gateway.content.update(props.record.id, { expectedVersion: props.record.version, title: title.value.trim(), summary: summary.value.trim(), blocks: canonicalBlocks.value }) : await gateway.content.create({ centerId: centerId.value.trim(), kind: kind.value, slug: slug.value.trim(), title: title.value.trim(), summary: summary.value.trim(), blocks: canonicalBlocks.value }); notice.value = "已按服务端响应保存草稿。"; emit("saved", result.id); } catch (cause) { fail(cause); } finally { pending.value = false; } }
async function command(action: "submit" | "return" | "approve" | "publish" | "offline") { if (!gateway || !props.record) return; if ((action === "return" || action === "offline") && !reason.value.trim()) { error.value = "请填写原因。"; return; } pending.value = true; error.value = ""; try { const version = props.record.version; const result = action === "submit" ? await gateway.content.submitReview(props.record.id, { expectedVersion: version }) : action === "return" ? await gateway.content.returnDraft(props.record.id, { expectedVersion: version, reason: reason.value.trim() }) : action === "approve" ? await gateway.content.approvePublication(props.record.id, { expectedVersion: version }) : action === "publish" ? await gateway.content.publish(props.record.id, { expectedVersion: version, confirmed: true }) : await gateway.content.offline(props.record.id, { expectedVersion: version, reason: reason.value.trim() }); notice.value = "服务端已更新内容状态。"; emit("saved", result.id); } catch (cause) { fail(cause); } finally { pending.value = false; } }
</script>

<template><section class="admin-content-editor" :aria-label="record ? '官网内容编辑器' : '新建官网内容'"><p v-if="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p><p v-if="reloadRequired" class="admin-inline-note">请重新读取服务端版本；不会自动覆盖当前草稿。</p><div class="admin-editor-grid"><label v-if="!record">中心 ID<input v-model="centerId" required></label><label v-if="!record">内容类型<select v-model="kind"><option value="article">新闻动态</option><option value="notice">通知公告</option><option value="flash">HSD 快讯</option></select></label><label v-if="!record">Slug<input v-model="slug" required></label><label class="is-wide">标题<input v-model="title"></label><label class="is-wide">摘要<textarea v-model="summary" rows="3" /></label><label class="is-wide">正文段落<textarea v-model="body" rows="6" /></label></div><div v-if="record?.blocks.some((block) => block.type === 'image')" class="admin-inline-note">图片块仅保留服务端 attachmentId 与替代文本，不使用本地媒体。</div><footer class="admin-content-editor__footer"><button class="button" type="button" :disabled="pending || reloadRequired" @click="save">保存草稿</button><button v-if="record?.canonicalStatus === 'draft'" type="button" :disabled="pending || reloadRequired" @click="command('submit')">提交审核</button><template v-if="isOwner && record"><label v-if="record.canonicalStatus === 'review' || record.canonicalStatus === 'published'">原因<input v-model="reason"></label><button v-if="record.canonicalStatus === 'review'" type="button" :disabled="pending" @click="command('return')">退回草稿</button><button v-if="record.canonicalStatus === 'review'" type="button" :disabled="pending" @click="command('approve')">审核通过</button><button v-if="record.canonicalStatus === 'pending_publication'" type="button" :disabled="pending" @click="command('publish')">发布内容</button><button v-if="record.canonicalStatus === 'published'" type="button" :disabled="pending" @click="command('offline')">确认下架</button></template><button v-if="reloadRequired" type="button" @click="emit('reload')">重新读取</button></footer></section></template>
